"""Alembic environment for the TimescaleDB instance (sensor_readings only).

This is a separate migration chain from `migrations/` (main Postgres: tenants/users/
facilities) with its own `alembic_version` table, because sensor_readings lives on a
physically different managed database — see app/core/config.py. `target_metadata` is
left as None: this chain is hand-written only, never autogenerated, so there's no value
in coupling it to the shared `Base.metadata` that also holds the main chain's tables.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

from app.core.config import settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def run_migrations_offline() -> None:
    context.configure(
        url=settings.timescale_migration_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable: AsyncEngine = create_async_engine(
        settings.timescale_migration_url, pool_pre_ping=True
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
